### ISSUE TITLE
Одинарный ресайз фигуры приводит к формированию 2-х Action-ов

### ISSUE THREAD

**Issue by alexey-malov** [Warboss-rus/MFCTest#10]
1. Вставить треугольник (или другую фигуру)
2. Отресайзить его
3. Нажать Undo.
   Ожидается, что треугольник вернется к состоянию, в котором он был после вставки на сцену в п.1.
   Фактическое поведение: треугольник отресайзится во центру своего текущего положения. Для того, чтобы он вернулся к состоянию п.1, надо еще раз нажать на Undo

**Comment by Warboss-rus** [comment]
Fixed https://github.com/Warboss-rus/MFCTest/commit/345dfdb1971f06d8c32d02f5c54b2754043f8b2c
