### ISSUE TITLE
При нажатии Delete программа падает

### ISSUE THREAD

**Issue by alexey-malov** [Warboss-rus/MFCTest#11]
1. Добавить фигуру на сцену.
2. Выделить ее.
3. Нажать клавишу Delete.
   Программа упадет из-за обращения к нулевому указателю

**Comment by Warboss-rus** [comment]
Fixed https://github.com/Warboss-rus/MFCTest/commit/345dfdb1971f06d8c32d02f5c54b2754043f8b2c
