### ISSUE TITLE
shared_ptr лучше рекомендуется принимать по константной ссылке

### ISSUE THREAD

**Issue by alexey-malov** [Warboss-rus/MFCTest#13]
Функциям, принимающе shared_ptr в качестве параметра, следует принимать его по константной ссылке, чтобы не увеличивать и не уменьшать счетчик ссылок при создании временного объекта и его разрушении (достаточно трудоемкая операция, т.к. используются команды, выполняющие атомарный инкремент/декремент)

**Comment by Warboss-rus** [comment]
Fixed https://github.com/Warboss-rus/MFCTest/commit/345dfdb1971f06d8c32d02f5c54b2754043f8b2c
