### ISSUE TITLE
После открытия документа не происходит перерисовка View

### ISSUE THREAD

**Issue by alexey-malov** [Warboss-rus/MFCTest#3]
1. Сохранить документ с несколькими фигурами
2. Перезапустить приложение
3. Открыть сохраненный документ
4. Пока не сделаешь resize или не уберешь окно за пределы области экрана, view не будет перерисован

**Comment by Warboss-rus** [comment]
https://github.com/Warboss-rus/MFCTest/commit/2ddcf04941a4408ded1121691ddc3868742ac583
