### ISSUE TITLE
Модель зависит от приложения и ведет себя как синглтон

### ISSUE THREAD

**Issue by alexey-malov** [Warboss-rus/MFCTest#5]
Класс CModel предоставляет статический метод GetModel(), который обращается к Application за активным документом.
Фактически, модули нижнего уровня начинают зависеть от модулей верхнего, а это плохо.

Как результат, классы, зависящие от модели (те же Action-ы), сложно будет автоматически протестировать, поскольку для их запуска придется каждый раз настраивать объект Application

Лучше сделать следующим образом: класс модели должен реализовывать определенный интерфейс, а action-ы получали бы в своем конструкторе этот интерфейс, через который бы и выполняли действия над моделью

**Comment by Warboss-rus** [comment]
Исправлено https://github.com/Warboss-rus/MFCTest/commit/a7cd09c8d84817c17a3ddf42ba67e07fdedaf4cf
