### ISSUE TITLE
Action-ы следует сделать частью модели, а не контроллера

### ISSUE THREAD

**Issue by alexey-malov** [Warboss-rus/MFCTest#6]
Логирование списка действий - это часть бизнес-логики приложения, поэтому правильнее их сделать частью модели, а не контроллера.
Ну и создание Action-ов - это тоже прерогатива модели.

Контроллер должен быть всего лишь связующим звеном между моделью и представлением.

Что можно выделить, так это историю команд (управляет списком команд, позволяет добавлять в список произвольные команды, реализующие интерфейс IAction, при Undo/Redo вызывает соотв. методы текущих команд). Также History может предоставлять методы, позволяющие определить доступность операций 
Вот примерно, как это может выглядеть.
![model_with_history](https://cloud.githubusercontent.com/assets/6040682/6227763/e8c34238-b6b4-11e4-97cc-9964845c263f.png)
Undo и Redo в данный момент.

Для внешнего мира (для контроллера) модель предоставляет интерфейс IModel. Реализация методов этого интерфейса создает Action-ы и добавляет их в историю и выполняет.
Action-ам же передается внутренний интерфейс модели IModelInternal, используя который модель позволяет действиям выполнять и отменять операции.

Вовсе не обязательно, чтобы интерфейс IModel и IModelInternal были реализованы одним и тем же классом модели. Можно, сделать так, чтобы реализация IModelInternal была частью модели (композиция). В этом случае IModelInternal будет, фактически, играть роль доменной модели (модель предметной области), а IModel - т.н. Application Model (или Presentation Model в некоторых источниках).

**Comment by Warboss-rus** [comment]
Исправлено https://github.com/Warboss-rus/MFCTest/commit/a7cd09c8d84817c17a3ddf42ba67e07fdedaf4cf
