### ISSUE TITLE
Исправить предупреждения компилятора

### ISSUE THREAD

**Issue by alexey-malov** [Warboss-rus/MFCTest#7]
```
bool CRectangle::IsOnFigure(unsigned int x, unsigned int y) const
{
    int left = m_centerX - m_width / 2;
    int right = m_centerX + m_width / 2;
    int top = m_centerY - m_height / 2;
    int bottom = m_centerY + m_height / 2;
    return (x > left && x < right && y > top && y < bottom); // Signed unsigned mismatch
}
```

Сравнение знаковых и беззнаковых чисел чревато ошибками, т.к. знаковый аргумент неявно приводится к беззнаковому типу и отрицательные числа превращаются в большие положительные

**Comment by alexey-malov** [comment]
```
int CMainFrame::OnCreate(LPCREATESTRUCT lpCreateStruct)
{
    if (CFrameWndEx::OnCreate(lpCreateStruct) == -1)
        return -1;

    BOOL bNameValid;
```

bNameValid - неиспользуемая переменная

**Comment by alexey-malov** [comment]
```
 str = new char[pFile->GetLength() + 1]; // 'initializing' : conversion from 'ULONGLONG' to 'unsigned int', possible loss of data
```

Оператор new [] принимает аргумент типа size_t, который на 32-битной платформе 32-битный. Размер файла же - 64 битный и может получиться так, что при размере файла больше 4 гигабайт произойдет усечение верхих разрядов.

**Comment by alexey-malov** [comment]
```
pFile->Read(str, pFile->GetLength() + 1); // conversion from 'ULONGLONG' to 'UINT', possible loss of data
```

Аналогичная фигня

**Comment by alexey-malov** [comment]
```	char* str = NULL;
	try
	{
		...
	}
	catch (std::exception) {}
	if (str) delete[] str;
```
-Исключения следует ловить по константной ссылке (чтобы не происходила "срезка", когда происходит выбрасывание исключения дочернего класса).
-проверять на null str здесь не имеет смысла, т.к. delete нулевого указателя безопасен.
-Использовать vector<char> вместо сырого массива было бы уместнее.

**Comment by Warboss-rus** [comment]
Исправлено https://github.com/Warboss-rus/MFCTest/commit/6828856ad929dd64388351bd8000495a02148657
