### ISSUE TITLE
Замечания по загрузке модели

### ISSUE THREAD

**Issue by alexey-malov** [Warboss-rus/MFCTest#8]
Лучше не закрывай issues, т.к. прав переоткрыть их у меня нет

```
    char* str = NULL;
    try
    {
        ...
    }
    catch (std::exception) {}
    if (str) delete[] str;
```

-Исключения следует ловить по константной ссылке (чтобы не происходила "срезка", когда происходит выбрасывание исключения дочернего класса).
-проверять на null str здесь не имеет смысла, т.к. delete нулевого указателя безопасен.
-Использовать vector<char> вместо сырого массива было бы уместнее.

**Comment by Warboss-rus** [comment]
Исправлено https://github.com/Warboss-rus/MFCTest/commit/6828856ad929dd64388351bd8000495a02148657

**Comment by Warboss-rus** [comment]
Исправлено https://github.com/Warboss-rus/MFCTest/commit/6828856ad929dd64388351bd8000495a02148657
